// data.js - product list for LittleLearners
// Each product includes: id, name, category, price, ageGroup, rating, description, image, alt, availability, learningBenefits
window.PRODUCTS = [
  {
    id: 1,
    name: "Solar System Discovery Kit",
    category: "STEM & Science",
    price: 34.99,
    ageGroup: "7–10",
    rating: 4.8,
    description: "A hands-on kit with planetary models, facts cards and activities to explore the solar system.",
    image: "https://images.unsplash.com/photo-1454789548928-9efd52dc4031?auto=format&fit=crop&w=800&q=80",
    alt: "Solar system model and planets for kids",
    availability: "In stock",
    learningBenefits: "Astronomy basics, fine motor skills, vocabulary"
  },
  {
    id: 2,
    name: "Magnetic Science Tiles",
    category: "STEM & Science",
    price: 44.00,
    ageGroup: "3–6",
    rating: 4.7,
    description: "Colorful magnetic tiles for open-ended building, early STEM concepts and spatial reasoning.",
    image: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=800&q=80",
    alt: "Children building with magnetic tiles",
    availability: "In stock",
    learningBenefits: "STEM, creativity, spatial awareness"
  },
  {
    id: 3,
    name: "Dinosaur Fossil Dig Kit",
    category: "STEM & Science",
    price: 22.50,
    ageGroup: "5–8",
    rating: 4.6,
    description: "Excavate realistic 'fossils' and learn paleontology basics with safe digging tools.",
    image: "https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=800&q=80",
    alt: "Kids uncovering dinosaur fossils in a dig kit",
    availability: "In stock",
    learningBenefits: "Scientific method, patience, fine motor skills"
  },
  {
    id: 4,
    name: "Wooden Number Puzzle",
    category: "Math & Numbers",
    price: 18.00,
    ageGroup: "3–5",
    rating: 4.5,
    description: "Smooth wooden puzzle pieces that teach numbers, counting and number recognition.",
    image: "https://images.unsplash.com/photo-1517686469429-8c3b7e6a9f90?auto=format&fit=crop&w=800&q=80",
    alt: "Wooden number puzzle for toddlers",
    availability: "In stock",
    learningBenefits: "Counting, number recognition, hand-eye coordination"
  },
  {
    id: 5,
    name: "Alphabet Learning Board",
    category: "Reading & Language",
    price: 24.99,
    ageGroup: "3–6",
    rating: 4.7,
    description: "Interactive alphabet board with letters, pictures and practice prompts to build early literacy.",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=800&q=80",
    alt: "Alphabet learning board for kids",
    availability: "In stock",
    learningBenefits: "Letter recognition, phonics, vocabulary"
  },
  {
    id: 6,
    name: "Kids Microscope",
    category: "STEM & Science",
    price: 39.99,
    ageGroup: "7–10",
    rating: 4.6,
    description: "Child-friendly microscope with prepared slides and hands-on experiment ideas.",
    image: "https://images.unsplash.com/photo-1581093588401-3d9f1b18a7ff?auto=format&fit=crop&w=800&q=80",
    alt: "Children's microscope with slides",
    availability: "Limited stock",
    learningBenefits: "Observation skills, biology basics, curiosity"
  },
  {
    id: 7,
    name: "Build Your Own Robot Kit",
    category: "STEM & Science",
    price: 69.00,
    ageGroup: "8–10",
    rating: 4.9,
    description: "A beginner robot kit with snap-together parts, simple circuits and programmable moves.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    alt: "Kids building a small robot kit",
    availability: "In stock",
    learningBenefits: "Basic engineering, problem solving, sequencing"
  },
  {
    id: 8,
    name: "World Map Puzzle",
    category: "Puzzles",
    price: 29.50,
    ageGroup: "6–10",
    rating: 4.6,
    description: "Colorful world map puzzle that introduces continents, countries and cultures.",
    image: "https://images.unsplash.com/photo-1520975921957-67b6a7f2f6d6?auto=format&fit=crop&w=800&q=80",
    alt: "Children assembling a world map puzzle",
    availability: "In stock",
    learningBenefits: "Geography, spatial reasoning, memory"
  },
  {
    id: 9,
    name: "Watercolor Art Set",
    category: "Arts & Creativity",
    price: 19.99,
    ageGroup: "4–8",
    rating: 4.5,
    description: "Non-toxic watercolor set with a brush, palette and thick paper for young artists.",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
    alt: "Children's watercolor art supplies",
    availability: "In stock",
    learningBenefits: "Color mixing, creativity, fine motor skills"
  },
  {
    id: 10,
    name: "Magnetic Math Board",
    category: "Math & Numbers",
    price: 27.00,
    ageGroup: "5–8",
    rating: 4.6,
    description: "Magnetic board with number tiles and activity cards to practice sums and patterns.",
    image: "https://images.unsplash.com/photo-1578926377163-9c7a5a3b8b2b?auto=format&fit=crop&w=800&q=80",
    alt: "Magnetic math board for kids",
    availability: "In stock",
    learningBenefits: "Addition, subtraction, early arithmetic"
  },
  {
    id: 11,
    name: "Animal Matching Cards",
    category: "Reading & Language",
    price: 12.00,
    ageGroup: "3–6",
    rating: 4.4,
    description: "Durable matching cards with animals, words and memory game activities.",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    alt: "Animal matching cards for children",
    availability: "In stock",
    learningBenefits: "Memory, vocabulary, matching skills"
  },
  {
    id: 12,
    name: "Junior Coding Robot",
    category: "STEM & Science",
    price: 79.00,
    ageGroup: "6–10",
    rating: 4.8,
    description: "Screen-free programmable robot that teaches sequencing and logic with cards.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    alt: "Small educational coding robot for kids",
    availability: "In stock",
    learningBenefits: "Sequencing, logic, early coding concepts"
  },
  {
    id: 13,
    name: "Storytelling Card Set",
    category: "Reading & Language",
    price: 14.50,
    ageGroup: "4–8",
    rating: 4.7,
    description: "Illustrated cards that prompt imaginative storytelling, sequencing and language skills.",
    image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=800&q=80",
    alt: "Storytelling prompt cards for children",
    availability: "In stock",
    learningBenefits: "Narrative skills, vocabulary, creativity"
  },
  {
    id: 14,
    name: "Wooden Shape Sorter",
    category: "Pretend Play",
    price: 16.00,
    ageGroup: "3–4",
    rating: 4.5,
    description: "Classic wooden shape sorter to teach shapes, colors and hand-eye coordination.",
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=800&q=80",
    alt: "Wooden shape sorter toy for toddlers",
    availability: "In stock",
    learningBenefits: "Shape recognition, fine motor, problem solving"
  },
  {
    id: 15,
    name: "Mini Chemistry Lab",
    category: "STEM & Science",
    price: 49.99,
    ageGroup: "8–10",
    rating: 4.6,
    description: "Safe, age-appropriate experiments introducing chemical reactions with clear guides.",
    image: "https://images.unsplash.com/photo-1581091870626-3c8d8f0f5d8e?auto=format&fit=crop&w=800&q=80",
    alt: "Mini chemistry lab kit for kids",
    availability: "Limited stock",
    learningBenefits: "Hands-on chemistry, observation, critical thinking"
  }
];
